name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: inventario_parcial
          MYSQL_ROOT_PASSWORD: 1234

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Wait for MySQL to be really ready
        run: |
          echo "esperando a que MySQL este listo"
          for i in {1..20}; do
            if mysql -h127.0.0.1 -uroot -p1234 -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL está listo."
              break
            fi
            echo "intento $i"
            sleep 3
          done

      - name: Configure Database
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: inventario_parcial
          DB_USERNAME: root
          DB_PASSWORD: 1234
        run: |
          php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: inventario_parcial
          DB_USERNAME: root
          DB_PASSWORD: 1234
        run: php artisan test

      - name: Tests passed!
        if: success()
        run: echo "Todas las pruebas pasaron correctamente."
